-- This file represents the SQL migration generated by Drizzle Kit
-- It creates the complete schema for the Auricrypt Plumbing App

CREATE TYPE "user_role" AS ENUM ('owner', 'manager', 'staff');
CREATE TYPE "job_status" AS ENUM ('scheduled', 'en_route', 'in_progress', 'completed', 'cancelled');
CREATE TYPE "invoice_status" AS ENUM ('draft', 'sent', 'paid', 'overdue', 'void');
CREATE TYPE "payment_status" AS ENUM ('pending', 'succeeded', 'failed', 'refunded');

CREATE TABLE "users" (
    "id" SERIAL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL UNIQUE,
    "password_hash" TEXT NOT NULL,
    "role" "user_role" NOT NULL DEFAULT 'staff',
    "phone_number" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "customers" (
    "id" SERIAL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT NOT NULL,
    "address_line_1" TEXT NOT NULL,
    "address_line_2" TEXT,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "zip_code" TEXT NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "products" (
    "id" SERIAL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "sku" TEXT NOT NULL UNIQUE,
    "description" TEXT,
    "unit_price" DECIMAL(10, 2) NOT NULL,
    "unit_type" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "jobs" (
    "id" SERIAL PRIMARY KEY,
    "customer_id" INTEGER NOT NULL REFERENCES "customers"("id"),
    "staff_id" INTEGER NOT NULL REFERENCES "users"("id"),
    "title" TEXT NOT NULL,
    "description" TEXT,
    "scheduled_start" TIMESTAMP NOT NULL,
    "scheduled_end" TIMESTAMP NOT NULL,
    "status" "job_status" NOT NULL DEFAULT 'scheduled',
    "location_notes" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "inventory" (
    "id" SERIAL PRIMARY KEY,
    "staff_id" INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "product_id" INTEGER NOT NULL REFERENCES "products"("id"),
    "quantity_on_hand" INTEGER NOT NULL DEFAULT 0,
    "last_updated" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "inventory_logs" (
    "id" SERIAL PRIMARY KEY,
    "inventory_id" INTEGER NOT NULL REFERENCES "inventory"("id"),
    "job_id" INTEGER REFERENCES "jobs"("id"),
    "quantity_change" INTEGER NOT NULL,
    "reason" TEXT NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "invoices" (
    "id" SERIAL PRIMARY KEY,
    "job_id" INTEGER NOT NULL REFERENCES "jobs"("id"),
    "customer_id" INTEGER NOT NULL REFERENCES "customers"("id"),
    "invoice_number" TEXT NOT NULL UNIQUE,
    "subtotal" DECIMAL(10, 2) NOT NULL,
    "tax_rate" DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
    "tax_amount" DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    "total_amount" DECIMAL(10, 2) NOT NULL,
    "status" "invoice_status" NOT NULL DEFAULT 'draft',
    "due_date" TIMESTAMP,
    "paid_at" TIMESTAMP,
    "notes" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "invoice_items" (
    "id" SERIAL PRIMARY KEY,
    "invoice_id" INTEGER NOT NULL REFERENCES "invoices"("id") ON DELETE CASCADE,
    "product_id" INTEGER REFERENCES "products"("id"),
    "description" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unit_price" DECIMAL(10, 2) NOT NULL,
    "line_total" DECIMAL(10, 2) NOT NULL
);

CREATE TABLE "payments" (
    "id" SERIAL PRIMARY KEY,
    "invoice_id" INTEGER NOT NULL REFERENCES "invoices"("id"),
    "payment_intent_id" TEXT UNIQUE,
    "amount" DECIMAL(10, 2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'usd',
    "status" "payment_status" NOT NULL DEFAULT 'pending',
    "payment_method" TEXT,
    "receipt_url" TEXT,
    "failure_reason" TEXT,
    "processed_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX "users_email_idx" ON "users" ("email");
CREATE INDEX "inventory_staff_product_idx" ON "inventory" ("staff_id", "product_id");
CREATE INDEX "invoice_items_invoice_idx" ON "invoice_items" ("invoice_id");
CREATE INDEX "jobs_staff_date_idx" ON "jobs" ("staff_id", "scheduled_start");